import './globals.css'
import type { Metadata } from 'next'
import StyledJsxRegistry from './lib/registry'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import { ThemeProvider } from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      
        <body className={inter.className}>
          <StyledJsxRegistry>{children}</StyledJsxRegistry>
        </body>
    

    </html>
  )
}
