
'use client'

import './globals.css'
import type { Metadata } from 'next'
import StyledJsxRegistry from './lib/registry'
import { Montserrat } from 'next/font/google'
import Header from './components/Header'
import { ThemeProvider } from 'styled-components'
import Footer from './components/footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = {
  colors: {
    primary: '#f73f01',
    secundary: '#777'
  }

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <ThemeProvider theme={theme}>
        <body className={montserrat.className}>
          <StyledJsxRegistry>
            <Header />
            {children}
            <Footer />
          </StyledJsxRegistry>
        </body>
      </ThemeProvider>



    </html>
  )
}
